name: "Setup pnpm/node/cache and install dependencies"

inputs:
  node_version:
    required: true
  pnpm_version:
    required: true
  npm_auth_token:
    required: true
  gh_token:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        token: ${{inputs.gh_token}}
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-
    - uses: actions/setup-node@v3
      with:
        node-version: ${{inputs.node_version}}
        registry-url: "https://registry.npmjs.org"
    - uses: pnpm/action-setup@v2
      with:
        version: ${{inputs.pnpm_version}}
    - run: pnpm install --frozen-lockfile --strict-peer-dependencies
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{inputs.npm_auth_token}}
